### ISSUE TITLE
`TypeError: 'pygame.font.Font' object is not subscriptable` when calling pygamepopup.init()

### ISSUE THREAD

**Issue by zjeffer** [Grimmys/pygame_popup_manager#3]
The full error:
```py
$ python main.py
pygame 2.0.3 (SDL 2.0.16, Python 3.10.1)
Hello from the pygame community. https://www.pygame.org/contribute.html
4
{'is_system_font': True, 'size': 20, 'is_bold': True}
{'is_system_font': True, 'size': 20, 'is_bold': True}
{'is_system_font': True, 'size': 20, 'is_bold': True}
{'is_system_font': True, 'size': 40, 'is_bold': True}
4
<pygame.font.Font object at 0x7f5529ad0a20>
Traceback (most recent call last):
  File "/home/zjeffer/Documents/school/howest-mct/semester5/research-project/chess-rl/main.py", line 79, in <module>
    m = Main(False)
  File "/home/zjeffer/Documents/school/howest-mct/semester5/research-project/chess-rl/main.py", line 33, in __init__
    self.GUI.start()
  File "/home/zjeffer/Documents/school/howest-mct/semester5/research-project/chess-rl/GUI/display.py", line 49, in start
    pygamepopup.init()
  File "/home/zjeffer/.local/lib/python3.10/site-packages/pygamepopup/initialization.py", line 13, in init
    fonts.init()
  File "/home/zjeffer/.local/lib/python3.10/site-packages/pygamepopup/fonts.py", line 21, in init
    if font["is_system_font"]:
TypeError: 'pygame.font.Font' object is not subscriptable
```

I added print statements to the `init` function in `fonts.py`.

```py
def init() -> None:
    """..."""
    print(len(default_fonts))
    for font_name, font in default_fonts.items():
        print(font)
    ...
```

As you can see in the error, the pygamepopup.init() seems to get called twice. The second time, the printing the fonts results in pygame.font.Font object. Both times, the amount of fonts is 4.

Why does it call the init function twice? It only gets called once in my code.

**Comment by zjeffer** [comment]
Nevermind, I called my `start()` function twice. Fixed.

**Comment by Grimmys** [comment]
No problem, I will still create a new issue referencing this one because it should not react this way one when you try to initialize the library twice.
